import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Container from "../components/Container/Container";
import Link from "next/link";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Payment App",
  description: "Generated by Pavel Hanys as a test task for a job application",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container className="flex flex-col min-h-screen h-full w-full">
          <header className="py-4 border-b border-gray-300 flex justify-between flex-wrap gap-2 items-center">
            <Link href="/" className="font-bold text-xl no-underline underline-none">Payment App</Link>
          </header>
          <main className="flex-grow py-4">
            {children}
          </main> 
          <footer className="flex sm:justify-end py-3 border-t border-gray-300 text-gray-400">
            <span>
                made by <Link href="https://hanys.vercel.app" target="_blank">Pavel Hanys</Link>
              </span>
          </footer>
        </Container>
      </body>
    </html>
  );
}
